### PR TITLE
Password store module

### PR DESCRIPTION
**Pull request by cmauf**
Moved password methods to own store module.

What to test: 
- [ ] check that registration still works
- [x] check that password change in profile works
- [x] check that password reset works

### CODE REVIEW

**Comment by LAYAIraq** [comment]
runs with backend march-22

**Comment by cmauf** [comment]
clarification: password reset in `login.vue` should be checked

**Comment by cmauf** [comment]
> passwort rst via admin runs with backend march-22 once per user, but not a second time (?)

what exactly does not seem to work? password and token are reset each time when I test it

**Comment by LAYAIraq** [comment]
Registration says "Name is already taken" - even though it isn't.
Setting new password in profile works.
Password reset "works" just like in user-pwd-reset. It doesn't set the new password in the database, login not possible.

**Pull request merged**
