### PR TITLE
Editor role

### PR DESCRIPTION
**Pull request by cmauf**
Created possibility to apply for authorship, introduced editor role and voting interface

make sure to revisit [Backend changes](https://github.com/LAYAIraq/LAYA-Iraq-Backend/pull/36) first

## What to test
- [x] unit tests succeed
- [x] non-authors can put an application down
- [x] non-authors can edit their application
- [x] authors cannot apply
- [x] editors see Editor Panel
- [x] editors can vote on existing applications
- [x] editors can change their decision

### CODE REVIEW

**Comment by Distaly** [comment]
I was not sure how to test backend changes? Only noted bugs here:
- Applications seems to be global? All non-author users see the same applicaton in their profile!
- User gets no feedback when applying for author. Might wrongly assume did not go through.


Unbenannt
- Headline is always english.
- Application text wrongly centered.
- All text brokenly centered on arabic and kurdish.
Unbenannt
- Administrator cant vote on editor (might be intentional?)
- Editors are not notified when applicants edit their application (might be a use case for the notifications section).
- There seems to be a bug with the admin panel? New users are not added. Might not be related to this branch, need to check later. Therefore did not yet check what happens when threshhold is passed.

**Comment by cmauf** [comment]
> I was not sure how to test backend changes? 

use loopback explorer that is exposed at `localhost:3001/explorer` in `development` mode

>     * User gets no feedback when applying for author. Might wrongly assume did not go through.

UI changes, seems sufficient to me

>     * Administrator cant vote on editor (might be intentional?)

True, admin should only care about platform, not content.

>     * Editors are not notified when applicants edit their application (might be a use case for the notifications section).

TBI <#62>


>     * There seems to be a bug with the admin panel? New users are not added. Might not be related to this branch, need to check later. Therefore did not yet check what happens when threshhold is passed.

I cannot reproduce - use vuex manipulation from vue dev tools to check w/o altering database

**Comment by NVieregg** [comment]
Backend: editor-role
Frontend: editor-role

Currently for me, I get this error when filling out the application, even though I filled out the application text. 

laya-backend   | Request POST /api/applications failed: ValidationError: The `AuthorApplication` instance is not valid. Details: `applicationText` can't be blank (value: undefined).
laya-backend   |     at /LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:373:12
laya-backend   |     at AuthorApplication.<anonymous> (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/validations.js:579:11)
laya-backend   |     at AuthorApplication.next (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
laya-backend   |     at AuthorApplication.<anonymous> (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/validations.js:576:23)
laya-backend   |     at AuthorApplication.trigger (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
laya-backend   |     at AuthorApplication.Validatable.isValid (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/validations.js:542:8)
laya-backend   |     at /LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:369:9
laya-backend   |     at doNotify (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
laya-backend   |     at doNotify (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
laya-backend   |     at doNotify (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
laya-backend   |     at doNotify (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
laya-backend   |     at Function.ObserverMixin._notifyBaseObservers (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
laya-backend   |     at Function.ObserverMixin.notifyObserversOf (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
laya-backend   |     at Function.ObserverMixin._notifyBaseObservers (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
laya-backend   |     at Function.ObserverMixin.notifyObserversOf (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
laya-backend   |     at Function.ObserverMixin._notifyBaseObservers (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)



Also: when editing application text, it resets upon clicking "Save application". 
Upon reloading the page, the application disappears.

I will try again by resetting the database.

**Comment by NVieregg** [comment]
Ignore previous comment, database was faulty......

**Comment by NVieregg** [comment]
still not working after resetting database ....

**Comment by NVieregg** [comment]
Problem seems to lie within my backend, will try again

**Comment by cmauf** [comment]
> still not working after resetting database ....
> 
> error does not show up anymore (I don't know why), but new error when I try to Withdraw Application after filling out Application and 'Saving' (even though it doesn't get saved):
> 
> > laya-backend   | Request PATCH /api/applications/undefined/decide failed: Error: Application doesn`t exist!
> > laya-backend   |     at AuthorApplication.findById (/LAYA-Iraq-Backend/server/models/author-application.js:62:21)
> > laya-backend   |     at /LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1801:62
> > laya-backend   |     at /LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1737:9
> > laya-backend   |     at /LAYA-Iraq-Backend/node_modules/async/dist/async.js:1140:9
> > laya-backend   |     at /LAYA-Iraq-Backend/node_modules/async/dist/async.js:473:16
> > laya-backend   |     at eachOfArrayLike (/LAYA-Iraq-Backend/node_modules/async/dist/async.js:1057:9)
> > laya-backend   |     at eachOf (/LAYA-Iraq-Backend/node_modules/async/dist/async.js:1117:5)
> > laya-backend   |     at _asyncMap (/LAYA-Iraq-Backend/node_modules/async/dist/async.js:1133:5)
> > laya-backend   |     at Object.map (/LAYA-Iraq-Backend/node_modules/async/dist/async.js:1122:16)
> > laya-backend   |     at allCb (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1648:13)
> > laya-backend   |     at SQLiteDB. (/LAYA-Iraq-Backend/node_modules/loopback-connector-sqlite/lib/sqlite3db.js:703:7)
> > laya-backend   |     at /LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:250:22
> > laya-backend   |     at doNotify (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
> > laya-backend   |     at SQLiteDB.ObserverMixin._notifyBaseObservers (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
> > laya-backend   |     at SQLiteDB.ObserverMixin.notifyObserversOf (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
> > laya-backend   |     at cbForWork (/LAYA-Iraq-Backend/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:240:14)

problem is that it tries to decide on an application that has not yet persisted in database (hence the `undefined` it) - will add check to not call request when application has not yet been saved

**Comment by cmauf** [comment]
> So, now it works. Everything works, but one bug is occurring:
> 
> When a student fills out the application and saves it, and reloads the profile page (for whatever reason) the application disappears. This does not happen if the student simply changes pages to, for example, courses.
> 
> Merge can be approved as soon as this bug is handled.

This happens because actual database manipulation is done in the `beforeDestroy` hook. Idea was that if a user makes many changes, we reduce the amount of HTTP requests sent to backend. Downside is inherent to Vue: Vue instance is not unmounted when user refreshes (see [this stackoverflow question](https://stackoverflow.com/questions/61339283/why-beforedestory-is-not-called-while-refresh-but-created-gets-called)) - hence no persistence is done. Since this not only occurs in this case, but in several others, we should discuss the way to handle changes to database in general and merge regardless.

**Pull request merged**
